#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program moves the robot forward, them the robot abruptly turns left, this iteration makes the robot move in a direction, making a square

                            ROBOT CONFIGURATION: LEGO EV3 REM Bot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                [Description]
    MotorC        	leftMotor           LEGO EV3 Motor	  Left side motor
    MotorB       	rightMotor          LEGO EV3 Motor	  Right side motor (reversed)
------------------------------------------------------------------------------------------------*/

task main()
{


		// Turn left at full power for 0.75 seconds
	setMotorSpeed(leftMotor, 200);	//Set the leftMotor (motor1) to full power forward (200)
	setMotorSpeed(rightMotor, 200);
	sleep(750);			//Wait for .75 second before continuing on in the program.

	setMotorSpeed(leftMotor, 50); //moves robot to the left
	setMotorSpeed(rightMotor, 50);
	sleep(750);

	setMotorSpeed(leftMotor, 50); //moves robot forward
	setMotorSpeed(rightMotor, 50);
	sleep(750);

	setMotorSpeed(leftMotor, 50);//moves robot to the left
		setMotorSpeed(rightMotor, 50);
		sleep(750);

			setMotorSpeed(leftMotor, 50); //moves robot forward
	setMotorSpeed(rightMotor, -50);
	sleep(750);

	setMotorSpeed(leftMotor, 50);//moves robot to the left
		setMotorSpeed(rightMotor, -50);
		sleep(750);

		setMotorSpeed(leftMotor, 200); //moves robot forward
	setMotorSpeed(rightMotor, 200);
	sleep(750);

	setMotorSpeed(leftMotor, 50);//moves robot to the left
		setMotorSpeed(rightMotor, -50);
		sleep(750);





}//end
