#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     ultrasonicSensor, sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turn90(long nMotorRatio, long dist, long power)
{
	setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, dist, power );
	sleep(1000);
}

task main()
{
	int counter = 0;

	do
	{

	while(SensorValue(ultrasonicSensor)>25)
	{
		setMotorSpeed(leftMotor, 50);
		setMotorSpeed(rightMotor, 50);

	}

	while(SensorValue(ultrasonicSensor)<10)
	{

		setMotorSpeed(leftMotor, -50);
		setMotorSpeed(rightMotor, -50);
		sleep(500);

		turn90(35, 0, -50);

		counter++;

	}
}while(counter != 3);

		setMotorSpeed(leftMotor, 50);
		setMotorSpeed(rightMotor, 50);

		sleep(3000);
}
