#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colourSensor,   sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		setMotorSpeed(leftMotor, 100);
		setMotorSpeed(rightMotor, 100);
		sleep(2750);

		setMotorSpeed(leftMotor, 50);
		setMotorSpeed(rightMotor, -60);
		sleep(720);

		setMotorSpeed(leftMotor, 25);
		setMotorSpeed(rightMotor, 25);
		sleep(8750);
}
