#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colourSensor,   sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void square1();
void square2();

task main()
{
	int num;
	num=random(1);

	if(num==0)
	{
		square1();
	}
	else(num==1);
	{
		square2();
	}
}

void square1()
{
	int i;
	for(i=0; i<4; i++)
	{
		setMotorSpeed(leftMotor, 100);
		setMotorSpeed(rightMotor, 100);
		sleep(1000);

		setMotorSpeed(leftMotor, 50);
		setMotorSpeed(rightMotor, -60);
		sleep(360);
	}
}
void square2()
{
	int i;
	for(i=0; i<4; i++)
	{
		setMotorSpeed(leftMotor, 100);
		setMotorSpeed(rightMotor, 100);
		sleep(1000);

		setMotorSpeed(leftMotor, -60);
		setMotorSpeed(rightMotor, 50);
		sleep(360);
	}
}
