#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while (true)
	{

		int dir=10;

		if (getColorReflected(S3)<90)
		{
			setMotorSync(leftMotor, rightMotor,-dir,15);
			sleep(20);

		}
		else
		{
			setMotorSync(leftMotor, rightMotor,dir,25);
			sleep(120);

		}
	}

}//end main
