#pragma config(Sensor, S1,     Touchsensor,    sensorEV3_Touch)
#pragma config(Sensor, S3,     Colorsensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     Ultrasonicsensor, sensorNone)
#pragma config(Motor,  motorB,          Leftmotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          Rightmotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{


	while(getButtonPress(buttonEnter) >=0)
	{
		displayCenteredTextLine(1, "press a button");

		if(getButtonPress(buttonUp) > 0)
		{
			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,50);
			sleep(2000);

				//STOPS ROBOT
			setMotorSpeed(motorB ,0);
			setMotorSpeed(motorC ,0);
			sleep(1500);

			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,0);
			sleep(2000);

			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,50);
			sleep(2000);

				//STOPS ROBOT
			setMotorSpeed(motorB ,0);
			setMotorSpeed(motorC ,0);
			sleep(1500);

			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,0);
			sleep(2000);

				setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,50);
			sleep(2000);

				//STOPS ROBOT
			setMotorSpeed(motorB ,0);
			setMotorSpeed(motorC ,0);
			sleep(1500);

			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,0);
			sleep(2000);

				setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,50);
			sleep(2000);

				//STOPS ROBOT
			setMotorSpeed(motorB ,0);
			setMotorSpeed(motorC ,0);
			sleep(1500);

			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,0);
			sleep(2000);

		}//endif


			if(getButtonPress(buttonDown) > 0)//IF STATEMENT FOR IF THE USER ENTER
			{
				setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,50);
			sleep(2000);

			//STOPS ROBOT
			setMotorSpeed(motorB ,0);
			setMotorSpeed(motorC ,0);
			sleep(1500);

			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,0);
			sleep(1500);

			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,50);
			sleep(2000);

			//STOPS ROBOT
			setMotorSpeed(motorB ,0);
			setMotorSpeed(motorC ,0);
			sleep(1500);


			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,0);
			sleep(2000);

				setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,50);
			sleep(2000);

			//STOPS ROBOT
			setMotorSpeed(motorB ,0);
			setMotorSpeed(motorC ,0);
			sleep(1500);


			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,0);
			sleep(2000);

			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,50);
			sleep(2000);

			//STOPS ROBOT
			setMotorSpeed(motorB ,0);
			setMotorSpeed(motorC ,0);
			sleep(1500);


			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,0);
			sleep(2000);

		 }//endif


			if(getButtonPress(buttonRight) > 0)//IF STATEMENT FO IF THE USER ENTER
			{
			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,50);
			sleep(2000);

			//STOPS ROBOT
			setMotorSpeed(motorB ,0);
			setMotorSpeed(motorC ,0);
			sleep(1500);

			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,0);
			sleep(1500);

			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,50);
			sleep(2000);

			//STOPS ROBOT
			setMotorSpeed(motorB ,0);
			setMotorSpeed(motorC ,0);
			sleep(1500);


			//turns robot right
			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,0);
			sleep(2000);

			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,50);
			sleep(2000);

			//STOPS ROBOT
			setMotorSpeed(motorB ,0);
			setMotorSpeed(motorC ,0);
			sleep(1500);


			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,0);
			sleep(2000);

			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,50);
			sleep(2000);

			//STOPS ROBOT
			setMotorSpeed(motorB ,0);
			setMotorSpeed(motorC ,0);
			sleep(1500);


			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,0);
			sleep(2000);

		}//endif3

		if(getButtonPress(buttonLeft) > 0)
			{
			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,50);
			sleep(2000);

			//STOPS ROBOT
			setMotorSpeed(motorB ,0);
			setMotorSpeed(motorC ,0);
			sleep(1500);

			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,0);
			sleep(1500);

			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,50);
			sleep(2000);

			//STOPS ROBOT
			setMotorSpeed(motorB ,0);
			setMotorSpeed(motorC ,0);
			sleep(1500);


			//turns robot right
			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,0);
			sleep(2000);

			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,50);
			sleep(2000);

			//STOPS ROBOT
			setMotorSpeed(motorB ,0);
			setMotorSpeed(motorC ,0);
			sleep(1500);


			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,0);
			sleep(2000);

			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,50);
			sleep(2000);

			//STOPS ROBOT
			setMotorSpeed(motorB ,0);
			setMotorSpeed(motorC ,0);
			sleep(1500);


			setMotorSpeed(motorB ,50);
			setMotorSpeed(motorC ,0);
			sleep(2000);
     }//endif4


}//endwhile

}
