#pragma config(Sensor, S1,     touch,          sensorEV3_Touch)
#pragma config(Sensor, S2,     gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S3,     colour,         sensorEV3_Color)
#pragma config(Sensor, S4,     ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Motor,  motorC,          Rightmotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          Leftmotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//while loop
	while(true)
	{
	//if statement for if the gyro sensor detects a change in motion > 3 degrees
	if(getGyroDegrees(S2) > 3)
	{
		setMotorSpeed(motorC , 50);
		setMotorSpeed(motorD , 50);
  }//endif

	if(getGyroDegrees(S2) < 3)
	{
		setMotorSpeed(motorC , -50);
		setMotorSpeed(motorD , -50);
  }//endif

	}//endwhile

}
