#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rearMotor,     tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	long power=0;
	long rear_motor_power=100;
	int tracker=0;

	while(true)
	{
				setMotorSpeed(rearMotor, rear_motor_power);

				setMotorSyncEncoder(leftMotor, rightMotor, 0, 1000,power);

				//if gyro reading is greater than 0, it powers at 100
				if(getGyroRate(S2)>0)
				{
					power=100;
			    wait1Msec(500);//waits 500 milliseconds
			  }//end if
				else
				{

					if(getGyroRate(S2)<0) //if gyro reading is less than 0, it powers at 0
					{
				   	power=0;
			     	wait1Msec(500);//waits 500 milliseconds
			    }//end if
			  }//end else
			  if(tracker==1)
			  {
			  	tracker=0;
			  	rear_motor_power=100;
			  }//end if
			  else
			  {
			  	tracker=1;
			  	rear_motor_power=-100;
			  }//end else
	}//End while
}//End main()
