#pragma config(Motor,  motorA,          amMotor,       tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setMotorSyncTime(tMotor nMotorOne, tMotor nMotorTwo, long nTurnRatio,long nSignedPower)
{
	setMotorSync(leftMotor, rightMotor,50,60);
	sleep(1000);

	setMotorSync(leftMotor, rightMotor,100,60);
	sleep(2000);

}
task main()
{

setMotorSyncTime('tMotor' 'nMotorOn'; 'tMotor' 'nMotorTwo'; 'nTurnRatio'; 'nSignedPower';);

}
